import { Product } from "./types";

import leatherBagImg from "@/assets/products/leather-bag.jpg";
import spiceCollectionImg from "@/assets/products/spice-collection.jpg";
import ceramicTeaSetImg from "@/assets/products/ceramic-tea-set.jpg";
import bambooBasketImg from "@/assets/products/bamboo-basket.jpg";
import bluetoothSpeakerImg from "@/assets/products/bluetooth-speaker.jpg";
import honeyJarImg from "@/assets/products/honey-jar.jpg";
import cottonScarvesImg from "@/assets/products/cotton-scarves.jpg";
import solarLanternImg from "@/assets/products/solar-lantern.jpg";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Handcrafted Leather Bag",
    description: "Premium quality handcrafted leather bag from artisan workshops. Perfect for everyday use with durable stitching and elegant design.",
    price: 89.99,
    qualityLabel: "high",
    verified: true,
    images: [leatherBagImg],
    category: "Fashion",
    location: "Marrakech, Morocco",
    lastUpdated: "2026-04-08",
    rating: 4.8,
    reviewCount: 124,
  },
  {
    id: "2",
    name: "Organic Spice Collection",
    description: "Curated set of 12 organic spices sourced directly from local farmers. Includes turmeric, saffron, cumin, and more.",
    price: 34.5,
    qualityLabel: "high",
    verified: true,
    images: [spiceCollectionImg],
    category: "Food & Beverages",
    location: "Kerala, India",
    lastUpdated: "2026-04-07",
    rating: 4.9,
    reviewCount: 89,
  },
  {
    id: "3",
    name: "Ceramic Tea Set",
    description: "Beautiful hand-painted ceramic tea set featuring traditional designs. Includes teapot and 4 cups.",
    price: 62.0,
    qualityLabel: "high",
    verified: true,
    images: [ceramicTeaSetImg],
    category: "Home & Living",
    location: "Jingdezhen, China",
    lastUpdated: "2026-04-05",
    rating: 4.7,
    reviewCount: 56,
  },
  {
    id: "4",
    name: "Woven Bamboo Basket",
    description: "Eco-friendly bamboo basket woven by skilled artisans. Multi-purpose storage solution with natural charm.",
    price: 28.0,
    qualityLabel: "medium",
    verified: true,
    images: [bambooBasketImg],
    category: "Home & Living",
    location: "Bali, Indonesia",
    lastUpdated: "2026-04-06",
    rating: 4.5,
    reviewCount: 43,
  },
  {
    id: "5",
    name: "Bluetooth Portable Speaker",
    description: "Compact wireless speaker with 20-hour battery life. IPX7 waterproof rating and rich bass.",
    price: 45.99,
    qualityLabel: "medium",
    verified: false,
    images: [bluetoothSpeakerImg],
    category: "Electronics",
    location: "Shenzhen, China",
    lastUpdated: "2026-04-04",
    rating: 4.3,
    reviewCount: 201,
  },
  {
    id: "6",
    name: "Natural Honey Jar (500g)",
    description: "Pure unprocessed honey from mountain apiaries. Rich in antioxidants with a distinctive floral note.",
    price: 18.75,
    qualityLabel: "high",
    verified: true,
    images: [honeyJarImg],
    category: "Food & Beverages",
    location: "Manuka, New Zealand",
    lastUpdated: "2026-04-09",
    rating: 4.9,
    reviewCount: 167,
  },
  {
    id: "7",
    name: "Cotton Scarf Bundle",
    description: "Set of 3 lightweight cotton scarves in complementary colors. Perfect for all seasons.",
    price: 22.0,
    qualityLabel: "medium",
    verified: true,
    images: [cottonScarvesImg],
    category: "Fashion",
    location: "Istanbul, Turkey",
    lastUpdated: "2026-04-03",
    rating: 4.4,
    reviewCount: 78,
  },
  {
    id: "8",
    name: "Solar-Powered Lantern",
    description: "Eco-friendly solar lantern with warm LED light. Charges in 6 hours, lasts up to 12 hours.",
    price: 35.0,
    qualityLabel: "medium",
    verified: false,
    images: [solarLanternImg],
    category: "Electronics",
    location: "Nairobi, Kenya",
    lastUpdated: "2026-04-02",
    rating: 4.2,
    reviewCount: 34,
  },
];
